//
//  DerivationRecipeTemplates.ts
//  DiceKeys
//
//  Auto-generated by recipe.ts in the DiceKeys specification TypeScript project.
//  Mon, 01 Feb 2021 01:17:41 GMT
//
import {DerivationRecipe} from "./DerivationRecipe"

export const DerivationRecipeTemplateList: DerivationRecipe[] = [
	new DerivationRecipe("Password", "1Password", `{"allow":[{"host":"*.1password.com"}]}`),
	new DerivationRecipe("Password", "Apple", `{"allow":[{"host":"*.apple.com"},{"host":"*.icloud.com"}],"lengthInChars":64}`),
	new DerivationRecipe("Password", "Authy", `{"allow":[{"host":"*.authy.com"}]}`),
	new DerivationRecipe("Password", "Bitwarden", `{"allow":[{"host":"*.bitwarden.com"}]}`),
	new DerivationRecipe("Password", "Facebook", `{"allow":[{"host":"*.facebook.com"}]}`),
	new DerivationRecipe("Password", "Google", `{"allow":[{"host":"*.google.com"}]}`),
	new DerivationRecipe("Password", "Keeper", `{"allow":[{"host":"*.keepersecurity.com"},{"host":"*.keepersecurity.eu"}]}`),
	new DerivationRecipe("Password", "LastPass", `{"allow":[{"host":"*.lastpass.com"}]}`),
	new DerivationRecipe("Password", "Microsoft", `{"allow":[{"host":"*.microsoft.com"},{"host":"*.live.com"}]}`)  
];
